### ISSUE TITLE
Clojupyter Jupyter kernelspec is not installed in non-base conda environment

### ISSUE THREAD

**Issue by rbeesley** [clojupyter/clojupyter#104]
```none
(base) PS C:\Users\[REDACTED]> conda --version
conda 4.7.12
(base) PS C:\Users\[REDACTED]>
```

I created a new environment for clojupyter, activated, then installed clojupyter using conda:

```none
(base) PS C:\Users\[REDACTED]> conda create -n clojupyter
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter



Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate clojupyter
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS C:\Users\[REDACTED]> conda activate clojupyter
(clojupyter) PS C:\Users\[REDACTED]> conda install -c simplect clojupyter
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter

  added / updated specs:
    - clojupyter


The following NEW packages will be INSTALLED:

  attrs              pkgs/main/noarch::attrs-19.3.0-py_0
  backcall           pkgs/main/win-64::backcall-0.1.0-py37_0
  bleach             pkgs/main/win-64::bleach-3.1.0-py37_0
  ca-certificates    pkgs/main/win-64::ca-certificates-2019.10.16-0
  certifi            pkgs/main/win-64::certifi-2019.9.11-py37_0
  clojupyter         simplect/win-64::clojupyter-0.2.3-1
  colorama           pkgs/main/win-64::colorama-0.4.1-py37_0
  decorator          pkgs/main/noarch::decorator-4.4.1-py_0
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  entrypoints        pkgs/main/win-64::entrypoints-0.3-py37_0
  importlib_metadata pkgs/main/win-64::importlib_metadata-0.23-py37_0
  ipykernel          pkgs/main/win-64::ipykernel-5.1.3-py37h39e3cac_0
  ipython            pkgs/main/win-64::ipython-7.9.0-py37h39e3cac_0
  ipython_genutils   pkgs/main/win-64::ipython_genutils-0.2.0-py37_0
  ipywidgets         pkgs/main/noarch::ipywidgets-7.5.1-py_0
  jedi               pkgs/main/win-64::jedi-0.15.1-py37_0
  jinja2             pkgs/main/noarch::jinja2-2.10.3-py_0
  jsonschema         pkgs/main/win-64::jsonschema-3.1.1-py37_0
  jupyter_client     pkgs/main/win-64::jupyter_client-5.3.4-py37_0
  jupyter_core       pkgs/main/win-64::jupyter_core-4.6.1-py37_0
  libsodium          pkgs/main/win-64::libsodium-1.0.16-h9d3ae62_0
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markupsafe         pkgs/main/win-64::markupsafe-1.1.1-py37he774522_0
  maven              pkgs/main/win-64::maven-3.6.0-0
  mistune            pkgs/main/win-64::mistune-0.8.4-py37he774522_0
  more-itertools     pkgs/main/win-64::more-itertools-7.2.0-py37_0
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  nbconvert          pkgs/main/win-64::nbconvert-5.6.1-py37_0
  nbformat           pkgs/main/win-64::nbformat-4.4.0-py37_0
  notebook           pkgs/main/win-64::notebook-6.0.2-py37_0
  openjdk            pkgs/main/win-64::openjdk-8.0.152-h7382acf_1
  openssl            pkgs/main/win-64::openssl-1.1.1d-he774522_3
  pandoc             pkgs/main/win-64::pandoc-2.2.3.2-0
  pandocfilters      pkgs/main/win-64::pandocfilters-1.4.2-py37_1
  parso              pkgs/main/noarch::parso-0.5.1-py_0
  pickleshare        pkgs/main/win-64::pickleshare-0.7.5-py37_0
  pip                pkgs/main/win-64::pip-19.3.1-py37_0
  prometheus_client  pkgs/main/noarch::prometheus_client-0.7.1-py_0
  prompt_toolkit     pkgs/main/noarch::prompt_toolkit-2.0.10-py_0
  pygments           pkgs/main/noarch::pygments-2.4.2-py_0
  pyrsistent         pkgs/main/win-64::pyrsistent-0.15.4-py37he774522_0
  python             pkgs/main/win-64::python-3.7.5-h8c8aaf0_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pywin32            pkgs/main/win-64::pywin32-223-py37hfa6e2cd_1
  pywinpty           pkgs/main/win-64::pywinpty-0.5.5-py37_1000
  pyzmq              pkgs/main/win-64::pyzmq-18.1.0-py37ha925a31_0
  send2trash         pkgs/main/win-64::send2trash-1.5.0-py37_0
  setuptools         pkgs/main/win-64::setuptools-41.6.0-py37_0
  six                pkgs/main/win-64::six-1.13.0-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.30.1-he774522_0
  terminado          pkgs/main/win-64::terminado-0.8.2-py37_0
  testpath           pkgs/main/win-64::testpath-0.4.2-py37_0
  tornado            pkgs/main/win-64::tornado-6.0.3-py37he774522_0
  traitlets          pkgs/main/win-64::traitlets-4.3.3-py37_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_0
  wcwidth            pkgs/main/win-64::wcwidth-0.1.7-py37_0
  webencodings       pkgs/main/win-64::webencodings-0.5.1-py37_1
  wheel              pkgs/main/win-64::wheel-0.33.6-py37_0
  widgetsnbextension pkgs/main/win-64::widgetsnbextension-3.5.1-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0
  winpty             pkgs/main/win-64::winpty-0.4.3-4
  zeromq             pkgs/main/win-64::zeromq-4.3.1-h33f27b4_3
  zipp               pkgs/main/noarch::zipp-0.6.0-py_0


Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: - b'"post-link.bat: JARFILE=C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\pkgs\\clojupyter-0.2.3-1\\info\\recipe\\install-items\\clojupyter-standalone.jar" \nError: Could not find or load main class clojupyter.cmdline\n'
| DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter', env_name: 'clojupyter', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\[REDACTED]\scoop\apps\anaconda3\current\python.exe, args are ['C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\cwp.py', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\python.exe', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
done
(clojupyter) PS C:\Users\[REDACTED]> jupyter kernelspec list
Available kernels:
  jupyter    C:\Users\[REDACTED]\AppData\Roaming\jupyter\kernels\jupyter
  python3    C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter\share\jupyter\kernels\python3
(clojupyter) PS C:\Users\[REDACTED]>
```

Clojupyter Kernel isn't installed, and this line in particular seems to suggest the problem:

```none
Executing transaction: - b'"post-link.bat: JARFILE=C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\pkgs\\clojupyter-0.2.3-1\\info\\recipe\\install-items\\clojupyter-standalone.jar" \nError: Could not find or load main class clojupyter.cmdline\n'
```

It is further confirmed that it is not listed as an available kernel:

```none
(clojupyter) PS C:\Users\[REDACTED]> jupyter kernelspec list
Available kernels:
  jupyter    C:\Users\[REDACTED]\AppData\Roaming\jupyter\kernels\jupyter
  python3    C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter\share\jupyter\kernels\python3
(clojupyter) PS C:\Users\[REDACTED]>
```

This is installing on a new Windows machine. I was able to make this work on another machine and they are similar in OS builds and how I installed dependencies.

**Comment by klausharbo** [comment]
Hi Ryan - 

Thanks for reporting this.  

I can reproduce this problem on my Windows 10 machine: If I follow the steps outlined above I get the same error.  If then I do `conda activate base` and then `conda install -c simplect clojupyter` the install succeeds so my hypothesis right now is that the conda install procedure does correctly use a non-base environment in some some - or all - circumstances.  **Maybe you could check if you get the same result on your machine?**

Being able to use Clojupyter in multiple conda environments is important so I will take a look at how this can be made to work, although I can't say exactly when just now.

-Klaus.

**Comment by rbeesley** [comment]
It's possible that on the first machine I installed this, I installed it to base... in fact, as I was learning how to work with conda at the time, I probably did install to base as I didn't understand environments at that time.

I uninstalled Clojupyter from the clojupyter environment, and installed it in base. Then in the clojupyter environment I installed Jupyter. I was able to open Jupyter Labs from this environment and see that there is a Clojupyter kernel.

This surprises me a little sinch when I query about the kernelspecs available from the command line, I don't see conda-clojupyter in the environment:

```none
(base) PS C:\Users\[REDACTED]\OneDrive\Documents\Jupyter> conda activate clojupyter
(clojupyter) PS C:\Users\[REDACTED]\OneDrive\Documents\Jupyter> jupyter kernelspec list
Available kernels:
  jupyter    C:\Users\[REDACTED]\AppData\Roaming\jupyter\kernels\jupyter
  python3    C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter\share\jupyter\kernels\python3
(clojupyter) PS C:\Users\[REDACTED]\OneDrive\Documents\Jupyter> conda activate base
(base) PS C:\Users\[REDACTED]\OneDrive\Documents\Jupyter> jupyter kernelspec list
Available kernels:
  jupyter             C:\Users\[REDACTED]\AppData\Roaming\jupyter\kernels\jupyter
  conda-clojupyter    C:\Users\[REDACTED]\scoop\apps\anaconda3\current\share\jupyter\kernels\conda-clojupyter
  python3             C:\Users\[REDACTED]\scoop\apps\anaconda3\current\share\jupyter\kernels\python3
(base) PS C:\Users\[REDACTED]\OneDrive\Documents\Jupyter>
```

Perhaps unsurprisingly, starting the Clojupyter kernel from Jupyter Labs, launched from this clojupyter environment, it fails to instantiate the kernel:

```none
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Launching from the base environment, I had no problem starting the Clojure kernel from within Jupyter Labs...

I think the conclusion is that the environments don't work and it must be installed and ran from base right now.

**Comment by klausharbo** [comment]
Yes, I think you're right.  I'll leave the issue open and post here when it's fixed.

**Comment by klausharbo** [comment]
I took a look at this issue and believe have a fix which is now posted to the `master` branch.  I don't think the updates warrants a new version number as the change only affects conda users so I have simply uploaded new builds to Anaconda Cloud.  

New users will simply get the new versions when doing `conda install -c simplect clojupyter`.  If you have already conda-installed the existing version you can do `conda upgrade -c simplect clojupyter`.

-Klaus.

PS Interestingly, Github auto-closed the issue when I merged the update, I assume because I had a link to the issue in the commit message.  Very clever.

**Comment by rbeesley** [comment]
I did not go through an upgrade path as I my original intent was to install in an isolated environment. I uninstalled from base and reinstalled in the clojupyter environment I had configured, and it does seem to be working as expected now.

**Comment by klausharbo** [comment]
Ryan, that's good to hear, thanks for the feedback.  -Klaus.
