### ISSUE TITLE
Can't install kernel from another conda environment

### ISSUE THREAD

**Issue by rbeesley** [clojupyter/clojupyter#116]
I can install clojupyter to its own environment and run it from there:
1. ❯ conda activate clojupyter
2. ❯ conda install -c simplect clojupyter
```
...
Preparing transaction: done
Verifying transaction: done
Executing transaction: / b'        1 file(s) copied.\n        1 file(s) copied.\n'
\- DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter', env_name: 'clojupyter', mode: 'user', used_mode: 'user'DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\[REDACTED]\scoop\apps\anaconda3\current\python.exe, args are ['C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\cwp.py', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\python.exe', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
done
```
3. ❯ jupyter lab
```
[I 02:14:15.573 LabApp] JupyterLab extension loaded from C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter\lib\site-packages\jupyterlab
[I 02:14:15.574 LabApp] JupyterLab application directory is C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter\share\jupyter\lab
[I 02:14:15.698 LabApp] Serving notebooks from local directory: C:\Users\[REDACTED]\OneDrive\Source
[I 02:14:15.699 LabApp] The Jupyter Notebook is running at:
[I 02:14:15.699 LabApp] http://localhost:8888/?token=xxxxx0b6aa44571351aef299191b15145038c018a66xxxxx
[I 02:14:15.700 LabApp]  or http://127.0.0.1:8888/?token=xxxxx0b6aa44571351aef299191b15145038c018a66xxxxx
[I 02:14:15.700 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:14:15.915 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/[REDACTED]/AppData/Roaming/jupyter/runtime/nbserver-13952-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=xxxxx0b6aa44571351aef299191b15145038c018a66xxxxx
     or http://127.0.0.1:8888/?token=xxxxx0b6aa44571351aef299191b15145038c018a66xxxxx
[W 02:14:21.356 LabApp] Could not determine jupyterlab build status without nodejs
[I 02:14:31.957 LabApp] Kernel started: 554b36f6-d58f-47a1-89fe-4f3d998faf5e
[I 02:14:46.454 LabApp] Adapting from protocol version 5.2 (kernel 554b36f6-d58f-47a1-89fe-4f3d998faf5e) to 5.3 (client).
```
```
Clojupyter (0.3.2)
[1]: (clojure-version)
[1]: "1.10.1"
```

-----

I deactivated the clojupyter environment, activating base, and installed the kernel there, using information I gathered from [this comment on StackOverflow](https://stackoverflow.com/a/44072803), but it fails to initialize the kernel:
1. ❯ conda deactivate env
2. ❯ jupyter kernelspec install C:\Users\[REDACTED]\scoop\apps\anaconda3\current\envs\clojupyter\share\jupyter\kernels\conda-clojupyter --user
```
[InstallKernelSpec] Installed kernelspec conda-clojupyter in C:\Users\[REDACTED]\AppData\Roaming\jupyter\kernels\conda-clojupyter
```
3. ❯ jupyter lab
```
❯ jupyter lab
[I 02:06:02.332 LabApp] JupyterLab extension loaded from C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyterlab
[I 02:06:02.333 LabApp] JupyterLab application directory is C:\Users\[REDACTED]\scoop\apps\anaconda3\current\share\jupyter\lab
[I 02:06:02.403 LabApp] Serving notebooks from local directory: C:\Users\[REDACTED]\OneDrive\Source
[I 02:06:02.404 LabApp] The Jupyter Notebook is running at:
[I 02:06:02.404 LabApp] http://localhost:8888/?token=xxxxxdd2fef4861271c1122dbe0360da10bdba5fb0exxxxx
[I 02:06:02.405 LabApp]  or http://127.0.0.1:8888/?token=xxxxxdd2fef4861271c1122dbe0360da10bdba5fb0exxxxx
[I 02:06:02.405 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:06:02.564 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/[REDACTED]/AppData/Roaming/jupyter/runtime/nbserver-15708-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=xxxxxdd2fef4861271c1122dbe0360da10bdba5fb0exxxxx
     or http://127.0.0.1:8888/?token=xxxxxdd2fef4861271c1122dbe0360da10bdba5fb0exxxxx
[W 02:06:07.656 LabApp] Could not determine jupyterlab build status without nodejs
[E 02:06:12.688 LabApp] Failed to run command:
    ['java', '-cp', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\share\\jupyter\\kernels\\conda-clojupyter\\clojupyter-standalone.jar', 'clojupyter.kernel.core', 'C:\\Users\\[REDACTED]\\AppData\\Roaming\\jupyter\\runtime\\kernel-0dd6ae1e-5b81-497a-a5b0-ded64b654fbd.json']
        PATH='C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Library\\mingw-w64\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Library\\usr\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Library\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Scripts;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\condabin;C:\\Users\\[REDACTED]\\.dotnet\\tools\\.store\\powershell\\7.0.0\\powershell\\7.0.0\\tools\\netcoreapp3.1\\any\\win;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Scripts;C:\\Users\\[REDACTED]\\scoop\\shims;C:\\Users\\[REDACTED]\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\[REDACTED]\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\[REDACTED]\\.dotnet\\tools;C:\\Users\\[REDACTED]\\OneDrive\\Source\\PowerShell'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\[REDACTED]\\OneDrive\\Source', 'close_fds': False}

[E 02:06:12.692 LabApp] Uncaught exception POST /api/sessions?1585731972458 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1585731972458', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
        **kw)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 02:06:12.731 LabApp] Unhandled error
[E 02:06:12.731 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "131",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.83 Safari/537.36 Edg/81.0.416.41",
      "X-Xsrftoken": "2|699b20db|2c12a12fd85d784533c33c8470fb2f6a|1585726891",
      "Authorization": "token xxxxxdd2fef4861271c1122dbe0360da10bdba5fb0exxxxx",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|699b20db|2c12a12fd85d784533c33c8470fb2f6a|1585726891; username-localhost-8888=\"2|1:0|10:1585731970|23:username-localhost-8888|44:N2QxMzEyZGEzNGRkNDBkMGEwMDk3ZjIyMTAxMWNlMTY=|0fd5925ca778df35bda8be90d422860f65c2d2928b9eb6b28d2119bced3627a4\""
    }
[E 02:06:12.731 LabApp] 500 POST /api/sessions?1585731972458 (::1) 267.82ms referer=http://localhost:8888/lab
[E 02:06:18.863 LabApp] Failed to run command:
    ['java', '-cp', 'C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\envs\\clojupyter\\share\\jupyter\\kernels\\conda-clojupyter\\clojupyter-standalone.jar', 'clojupyter.kernel.core', 'C:\\Users\\[REDACTED]\\AppData\\Roaming\\jupyter\\runtime\\kernel-4e779b25-c77b-4b11-9836-fda0db621816.json']
        PATH='C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Library\\mingw-w64\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Library\\usr\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Library\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Scripts;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\bin;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\condabin;C:\\Users\\[REDACTED]\\.dotnet\\tools\\.store\\powershell\\7.0.0\\powershell\\7.0.0\\tools\\netcoreapp3.1\\any\\win;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Users\\[REDACTED]\\scoop\\apps\\anaconda3\\current\\Scripts;C:\\Users\\[REDACTED]\\scoop\\shims;C:\\Users\\[REDACTED]\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\[REDACTED]\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\[REDACTED]\\.dotnet\\tools;C:\\Users\\[REDACTED]\\OneDrive\\Source\\PowerShell'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\[REDACTED]\\OneDrive\\Source', 'close_fds': False}

[E 02:06:18.868 LabApp] Uncaught exception POST /api/sessions?1585731978810 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1585731978810', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\R[REDACTED]Bees\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
        **kw)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\[REDACTED]\scoop\apps\anaconda3\current\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 02:06:18.916 LabApp] Unhandled error
[E 02:06:18.916 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "131",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.83 Safari/537.36 Edg/81.0.416.41",
      "X-Xsrftoken": "2|699b20db|2c12a12fd85d784533c33c8470fb2f6a|1585726891",
      "Authorization": "token xxxxxdd2fef4861271c1122dbe0360da10bdba5fb0exxxxx",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|699b20db|2c12a12fd85d784533c33c8470fb2f6a|1585726891; username-localhost-8888=\"2|1:0|10:1585731978|23:username-localhost-8888|44:NDA3NDlkMTViMjU3NDhlMDhhMTg4NWU3NzUyM2JmNDQ=|16abc01e1e02b97a0cc1cb574058789b45f8d89dea314b56efb41b61d7c8d44a\""
    }
[E 02:06:18.916 LabApp] 500 POST /api/sessions?1585731978810 (::1) 99.65ms referer=http://localhost:8888/lab
[I 02:08:56.800 LabApp] Shutting down on /api/shutdown request.
[I 02:08:56.804 LabApp] Shutting down 0 kernels
```

-----

I was able to install a python kernel in another environment and installed in in base this way, so this should work based on the documentation I've read.

I was able to verify that the expected folder with kernel.json was made in the correct location and the paths referenced the correct files.

I suspect there are some assumptions made about where the kernel is in the path and trying to use the kernel this way it breaks those assumptions. What was also unusual about this process, was that when I try to create a new document or console using this kernel from the base environment, I'm presented with a dialog before it fails, but I don't have that with the python kernel.

This may be similar to what @meifish was seeing back in October in #99.

**Comment by rbeesley** [comment]
I also tried to change the startup class like what was being discussed in #112 with the AOT problem. This gave me a different error that Jupyter Labs was having trouble starting the kernel and it went into a loop of retries. Since this failed in a different way, it seems as though conda-clojupyter is "starting," so without deeper investigation yet, I'm inclined to think the problem is originating in the kernel with assumptions about folder structure and files.

**Comment by rbeesley** [comment]
Success!

```
Clojupyter (0.3.2)
[1]: (clojure-version)
[1]: "1.10.1"
```

-----

So, it looks like the Jupyter Labs environment has a dependency on openjdk. That isn't necessarily surprising, but I started digging into the stack trace of the failure and realized that it was failing to start the process... There was little else going on. I decided to test this by trying to execute `java -version` from the environment and realized that openjdk hadn't been added to that environment. I installed it and was able to run the kernel as expected.

This is probably documentation that would be worth adding to the instructions. I'll leave this bug open so that you can see this, but if you want to task me a work item to add the documentation I can since I have familiarity with the whole process now.

**Comment by klausharbo** [comment]
Hi Ryan -

I'm glad to hear you managed to find the issue.  To the best of my knowledge Jupyter as such does not depend on openjdk, but Clojupyter does since a JVM is required to run Clojure, obviously.  To build Clojupyter for Conda distribution a `meta.yaml` is generated

```
about:
  description: Clojupyter - Run Clojure in Jupyter
  home: https://github.com/clojupyter/clojupyter
  license: MIT
build:
  number: 1
  string: '1'
package:
  name: clojupyter
  version: 0.3.2
requirements:
  build:
  - openjdk=8
  - maven
  run:
  - openjdk=8
  - maven
  - ipywidgets
  - jupyterlab
  - notebook
  - qtconsole
  - widgetsnbextension
source:
  folder: install-items
```

which controls the conda build specifying version and build numbers *and* the dependencies for both build-time and run-time dependencies.  As you can see above, Clojupyter dependends on `openjdk` version 8.   This means that conda will install openjdk if it is not present in the current conda environment.  I don't know much about the workings of `jupyter install-spec` but I suspect it does not know anything about conda dependencies and so your environment was left '`openjdk`-less'...  

The jupyter error messages (stack dump) do leave quite a bit to be desired - if it had said 'kernel executable java not found in path' I'm sure you would have located the problem immediately, but that applies equally to all kernels.

I think it would be great if you were to improve the documentation for this! :-)  Thanks.

-Klaus.

**Comment by nighcoder** [comment]
Judging from the label and the lack of activity lately, I assume that this issue is solved.

@rbeesley, feel free to correct me and reopen it if that's not the case.
