### ISSUE TITLE
Does not work with native ARM64 (M1 Mac) conda

### ISSUE THREAD

**Issue by conchis** [clojupyter/clojupyter#146]
Not sure why this would require a specific machine architecture. Jupyter and native JVM both work fine.

```
(base) jonathan@Lucretius tryclj % conda install -c simplect/label/beta clojupyter
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - clojupyter

Current channels:

  - https://conda.anaconda.org/simplect/label/beta/osx-arm64
  - https://conda.anaconda.org/simplect/label/beta/noarch
  - https://conda.anaconda.org/simplect/osx-arm64
  - https://conda.anaconda.org/simplect/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
```

**Comment by nighcoder** [comment]
@conchis, most likely is the JVM that's arch dependent and that's a dependency of clojupyter.

Can you build the conda package locally and install it from there and see if it works for you?

**Comment by philiplopez** [comment]
I'm having the same problem on M1. Unfortunately, I'm extremely new to Jupiter and Anaconda (was hoping to try this out in VSCode). First time using any of these tools today.

However, with Anaconda installed (and conda activate...), I eventually figured out that I should probably try the following on an Apple Silicon (M1) machine under macOS 12.3.x:

`BUILDNUM=999 make conda-build`

Assuming that was the correct way to run the build (?), it resulted in the following error (looks like it doesn't have openjdk v8 for osx-arm64:

`
... (lein downloading dependencies)
Clojupyter v0.3.3-SNAPSHOT - Build Conda package

    Conda build failed.
    
    Conda build: exit(1).
    
    Conda build error output:
        ------------------------------------------------------------------------------------------------------------------------
        conda-build: INFO:conda_build.variants:Adding in variants from internal_defaults
        conda-build: INFO:conda_build.metadata:Attempting to finalize metadata for clojupyter
        conda-build: DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
        conda-build: DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/osx-arm64/repodata.json HTTP/1.1" 304 0
        conda-build: DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 304 0
        conda-build: DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/osx-arm64/repodata.json HTTP/1.1" 304 0
        conda-build: DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json HTTP/1.1" 304 0
        conda-build: DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/channeldata.json HTTP/1.1" 200 None
        conda-build: DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/channeldata.json HTTP/1.1" 200 None
        conda-build: Traceback (most recent call last):
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/environ.py", line 799, in get_install_actions
        conda-build:     actions = install_actions(prefix, index, specs, force=True)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        conda-build:     return f(*args, **kwds)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/plan.py", line 474, in install_actions
        conda-build:     txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        conda-build:     unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        conda-build:     final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 313, in solve_final_state
        conda-build:     ssc = self._add_specs(ssc)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 603, in _add_specs
        conda-build:     explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 555, in _get_package_pool
        conda-build:     pool = self.get_reduced_index(specs)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        conda-build:     return f(*args, **kwds)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 576, in get_reduced_index
        conda-build:     explicit_specs, features = self.verify_specs(explicit_specs)
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 288, in verify_specs
        conda-build:     raise ResolvePackageNotFound(bad_deps)
        conda-build: conda.exceptions.ResolvePackageNotFound: 
        conda-build:   - maven
        conda-build:   - openjdk=8
        conda-build: 
        conda-build: During handling of the above exception, another exception occurred:
        conda-build: 
        conda-build: Traceback (most recent call last):
        conda-build:   File "/opt/homebrew/anaconda3/bin/conda-build", line 11, in <module>
        conda-build:     sys.exit(main())
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 488, in main
        conda-build:     execute(sys.argv[1:])
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 477, in execute
        conda-build:     outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
        conda-build:     return build_tree(
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
        conda-build:     packages_from_this = build(metadata, stats,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 2051, in build
        conda-build:     output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 788, in expand_outputs
        conda-build:     for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/metadata.py", line 2120, in get_output_metadata_set
        conda-build:     conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/metadata.py", line 781, in finalize_outputs_pass
        conda-build:     fm = finalize_metadata(om, parent_metadata=parent_metadata,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 546, in finalize_metadata
        conda-build:     build_unsat, host_unsat = add_upstream_pins(m,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 386, in add_upstream_pins
        conda-build:     build_deps, build_unsat, extra_run_specs_from_build = _read_upstream_pin_files(m, 'build',
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 373, in _read_upstream_pin_files
        conda-build:     deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/render.py", line 138, in get_env_dependencies
        conda-build:     actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
        conda-build:   File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/conda_build/environ.py", line 801, in get_install_actions
        conda-build:     raise DependencyNeedsBuildingError(exc, subdir=subdir)
        conda-build: conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {'maven', 'openjdk=8'}
        ------------------------------------------------------------------------------------------------------------------------
    

exit(1)
make: *** [conda-build] Error 1
`

**Comment by thomasantony** [comment]
I was able to make some progress after adding the `conda-forge` channel as openjdk and maven are available there for apple silicon:

```
conda config --add channels conda-forge
```

**Comment by krukow** [comment]
Please install release 0.3.6 from https://clojars.org/clojupyter.

At the moment I don't have knowledge or bandwith to release with conda

**Comment by freder** [comment]
> Please install release 0.3.6 from https://clojars.org/clojupyter.

@krukow how does one do that?

**Comment by krukow** [comment]
Hey @freder @thomasantony @philiplopez @conchis  - apologies for the late reply - I'm maintaining this in my spare time.

I've been looking into this and unfortunately I can no longer support installation via conda. Instead I recommend building the latest version locally via the following commands (requires [clojure CLI and deps tools](https://clojure.org/guides/deps_and_cli)):

I've confirmed this works on Mac M1 and with latest version of jupyter lab

Instructions below:


## Build

Checkout [this repo](https://github.com/clojupyter/clojupyter) on the master branch and build an uberjar:

Building an uberjar:

```
clj -T:build uber

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
target/clojupyter-0.4.321-standalone.jar
```

## Install kernel

```
clj -M -m clojupyter.cmdline install --jarfile target/clojupyter-0.4.321-standalone.jar --ident clojupyter-0.4.321
```

Verify:

```
clj -M -m clojupyter.cmdline list-installs

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Clojupyter v0.4.321@321 - All Clojupyter kernels

    |              IDENT |                                          DIR |
    |--------------------+----------------------------------------------|
    | clojupyter-0.4.321 | ~/Library/Jupyter/kernels/clojupyter-0.4.321 |

exit(0)
```

## Check that everything works

Install jupyterlab if you haven't already. On MacOS you might do:
```
brew install jupyterlab
```

Validate that it's working:
```
jupyter lab --version
4.0.9
```


Now you can try a console:

```
jupyter-console --kernel=clojupyter-0.4.321
WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Jupyter console 6.6.3

Clojupyter (0.4.321)
```

Or you can run in jupyter lab (from this repo):

```
jupyter lab
```

then open a file like: examples/demo-clojupyter.ipynb and run all cells.

## Use clojupyter as a library as part of another program/library

You can also use this as a library - here's an example: https://github.com/krukow/edmondson

**Comment by krukow** [comment]
Closing: I will not be able to support releasing to Conda and all users should be familar with clojars since this is a clojure project.
