### ISSUE TITLE
Cannot connect to kernel

### ISSUE THREAD

**Issue by askonivala** [clojupyter/clojupyter#172]
I installed clojupyter with Conda but cannot connect to kernel. This is the error message I received:

```
[W 16:14:46.149 NotebookApp] Notebook Untitled.ipynb is not trusted
[I 16:14:46.203 NotebookApp] Kernel started: 02f49e5a-6309-4635-978d-73aff5b4bd6c, name: conda-clojupyter
[E 13:14:48.865 Clojupyter] c8r.messages -- Invalid message signature
[E 13:14:48.874 Clojupyter] c8r.util-actions -- 
                                        java.lang.Thread.run              Thread.java:  745
          java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
           java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                                                         ...                               
                           clojure.core.async/thread-call/fn                async.clj:  443
                                     clojupyter.zmq/start/fn                  zmq.clj:  108
                                      clojure.core.async/>!!                async.clj:  143
     clojure.core.async.impl.channels.ManyToManyChannel/put!             channels.clj:  143
                    clojure.core.async.impl.channels/chan/fn             channels.clj:  300
                                      clojure.core/map/fn/fn                 core.clj: 2742
                                                         ...                               
clojupyter.util-actions/wrap-report-and-absorb-exceptions/fn         util_actions.clj:  239
                                          clojure.core/apply                 core.clj:  665
                                                         ...                               
                                        clojure.core/comp/fn                 core.clj: 2569
         clojupyter.kernel.core/wrap-skip-shutdown-tokens/fn                 core.clj:   83
                                        clojure.core/comp/fn                 core.clj: 2569
                                     clojure.core/partial/fn                 core.clj: 2624
                                                         ...                               
                 clojure.spec.test.alpha/spec-checking-fn/fn                alpha.clj:  142
                                                         ...                               
                       clojupyter.messages/fn/frames->jupmsg             messages.clj:  288
java.lang.Exception: Invalid message signature

[E 13:14:48.888 Clojupyter] c8r.util-actions -- 
                                        java.lang.Thread.run              Thread.java:  745
          java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
           java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                                                         ...                               
                           clojure.core.async/thread-call/fn                async.clj:  443
                                     clojupyter.zmq/start/fn                  zmq.clj:  108
                                      clojure.core.async/>!!                async.clj:  143
     clojure.core.async.impl.channels.ManyToManyChannel/put!             channels.clj:  143
                    clojure.core.async.impl.channels/chan/fn             channels.clj:  300
                                      clojure.core/map/fn/fn                 core.clj: 2742
                                                         ...                               
clojupyter.util-actions/wrap-report-and-absorb-exceptions/fn         util_actions.clj:  239
                                          clojure.core/apply                 core.clj:  665
                                                         ...                               
                                        clojure.core/comp/fn                 core.clj: 2569
         clojupyter.kernel.core/wrap-skip-shutdown-tokens/fn                 core.clj:   83
                                        clojure.core/comp/fn                 core.clj: 2569
                                     clojure.core/partial/fn                 core.clj: 2624
                                                         ...                               
                 clojure.spec.test.alpha/spec-checking-fn/fn                alpha.clj:  142
                                                         ...                               
                       clojupyter.messages/fn/frames->jupmsg             messages.clj:  288
java.lang.Exception: Invalid message signature

Exception in thread "async-thread-macro-11" java.lang.AssertionError: Assert failed: handle-request - internal error (':shell_port' neq '')
(= channel-port req-port)
	at clojupyter.kernel.handle_event_process$handle_event_or_channel_error.invokeStatic(handle_event_process.clj:23)
	at clojupyter.kernel.handle_event_process$handle_event_or_channel_error.invoke(handle_event_process.clj:16)
	at clojupyter.kernel.handle_event_process$run_dispatch_loop.invokeStatic(handle_event_process.clj:52)
	at clojupyter.kernel.handle_event_process$run_dispatch_loop.invoke(handle_event_process.clj:40)
	at clojupyter.kernel.handle_event_process$start_channel_thread$fn__28145.invoke(handle_event_process.clj:61)
	at clojure.core.async$thread_call$fn__5737.invoke(async.clj:443)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[E 13:14:49.033 Clojupyter] c8r.zmq.heartbeat-process -- heartbeat: Polling ZeroMQ socket returned negative value - terminating.

```

My clojupyter version is the following:
```
# Name                    Version                   Build  Channel
clojupyter                0.3.2                         1    simplect

```

**Comment by krukow** [comment]
Hey @askonivala - apologies for the late reply. I'm maintaining this in my spare time.

I've been looking into this and unfortunately I can no longer support installation via conda. Instead I recommend building the latest version locally via the following commands (requires [clojure CLI and deps tools](https://clojure.org/guides/deps_and_cli)):

## Build

Checkout [this repo](https://github.com/clojupyter/clojupyter) on the master branch and build an uberjar:

Building an uberjar:

```
clj -T:build uber

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
target/clojupyter-0.4.321-standalone.jar
```

## Install kernel

```
clj -M -m clojupyter.cmdline install --jarfile target/clojupyter-0.4.321-standalone.jar --ident clojupyter-0.4.321
```

Verify:

```
clj -M -m clojupyter.cmdline list-installs

WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Clojupyter v0.4.321@321 - All Clojupyter kernels

    |              IDENT |                                          DIR |
    |--------------------+----------------------------------------------|
    | clojupyter-0.4.321 | ~/Library/Jupyter/kernels/clojupyter-0.4.321 |

exit(0)
```

## Check that everything works

Install jupyterlab if you haven't already. On MacOS you might do:
```
brew install jupyterlab
```

Validate that it's working:
```
jupyter lab --version
4.0.9
```


Now you can try a console:

```
jupyter-console --kernel=clojupyter-0.4.321
WARNING: parse-boolean already refers to: #'clojure.core/parse-boolean in namespace: omniconf.core, being replaced by: #'omniconf.core/parse-boolean
Jupyter console 6.6.3

Clojupyter (0.4.321)
```

Or you can run in jupyter lab (from this repo):

```
jupyter lab
```

then open a file like: examples/demo-clojupyter.ipynb and run all cells.

## Use clojupyter as a library as part of another program/library

You can also use this as a library - here's an example: https://github.com/krukow/edmondson

**Comment by vxe** [comment]
the example to use as a library does not seem to build:
* https://github.com/krukow/edmondson
```
~/tmp/edmondson
% clj -m clojupyter.cmdline install --ident mykernel-$RANDOM --jarfile clojupyter-standalone.jar
WARNING: Implicit use of clojure.main with options is deprecated, use -M
Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate clojupyter/cmdline__init.class, clojupyter/cmdline.clj or clojupyter/cmdline.cljc on classpath.

Full report at:
/var/folders/7d/9x94m_9d02lb5yxvjfv5c6gr0000gn/T/clojure-5720873611678733299.edn
```

on a simple hello world clj project the kernel builds but it seems to have class not found exception

```
[I 2024-07-05 14:56:22.251 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
Error: Could not find or load main class clojupyter.kernel.core
Caused by: java.lang.ClassNotFoundException: clojupyter.kernel.core
[W 2024-07-05 14:56:25.280 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-07-05 14:56:25.280 ServerApp] Kernel 30b4d1cd-b189-4206-9678-9b7bdd88c9d3 died, removing from map.
```

**Comment by krukow** [comment]
Hey, the krukow/edmondson repo should be built using the .`/script/go.sh` build script. See the docs for building locally here: https://github.com/krukow/edmondson/blob/main/doc/jupyter.md#local-prerequisites 

The reason the above command fails is that it does not include the "-A:jupyter" alias which ensures that clojupyter is on the classpath. If you read the "go.sh" script you'll see the final command:

```
/usr/local/bin/clojure -A:jupyter -m clojupyter.cmdline install --ident edmondson --jarfile $uber_jar
```
